###  Get washing machines
GET http://localhost:9000/washing-machines
Content-type: application/json


### - Start washing machine
POST http://localhost:9000/washing-machines/Samsung/start
Content-type: application/json

###
GET http://localhost:9000/washing-machines/Samsung/state
Content-type: application/json

###
GET http://localhost:9000/washing-machines/Samsung/power
Content-type: application/json

### - Capture power consumption
POST http://localhost:9000/washing-machines/Samsung/power
Content-type: application/json

{
  "consumption" :  30
}

### - Capture in batch mode
POST http://localhost:9000/washing-machines/Samsung/batch-power
Content-type: application/json

{
  "batchSize" :  5,
  "singleReadingAmount": 2,
  "totalNumberOfReadings": 30,
  "startDate" : "2017-10-01T09:45:00",
  "endDate": "2018-10-01T09:45:00"
}



############ Migrations ######################################
GET http://localhost:9000/migrations/running
Content-type: application/json

### - Start new migration
POST http://localhost:9000/migrations/start-new/onboarding
Content-type: application/json

{
  "numberOfChecklists" :  5,
  "newRevision": 2
}

###


